#specs for travis ci
language: python
dist: xenial
python: 
  - 3.6
  - 3.7

# get the dependencies
before_install:
  - pip install pipenv
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/trusty-media; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg --allow-unauthenticated; fi

stages:
  - test
  - name: version
   # if: branch = master

jobs:
  include:
    - stage: test
      install:
        - pipenv install --dev --ignore-pipfile --deploy
      script:
        - pipenv run pytest --cov-report xml --cov-report term
      after_success:
        - codecov -t $CC_TEST_REPORTER_ID
    - stage: version
      install:
        - pip install -e .
      script:
        - pytest