# specs for travis ci
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# get the dependencies
install:
  - pip install .
# install what we need for testing
before_install:
  - pip install pytest pytest-cov codecov
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

# script for tests... (eventually add coveralls)
script: 
  - pytest --cov=./moseq2
after_success:
  - codecov -t 120653e3-fb8e-4928-a751-bd4fdc880ff0
