#specs for travis ci
language: python
dist: trusty
os: linux
cache: false

stages:
  - latest-pipfile
  - latest-pip

jobs:
  include:
    - env: ISOLATED=true
      python: '3.6'
      stage: latest-pipfile
      before_install:
        - pip install pipenv
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/trusty-media; fi
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg --allow-unauthenticated; fi
      install:
        - pipenv install --dev --ignore-pipfile --deploy
      script:
        - pipenv run pytest --cov-report xml --cov-report term
      after_success:
        - codecov -t $CC_TEST_REPORTER_ID
    - env: ISOLATED=true
      dist: xenial
      sudo: true
      python: '3.7'
      stage: latest-pipfile
      before_install:
        - pip install pipenv
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/xerus-media; fi
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg --allow-unauthenticated; fi
      install:
        - pipenv install --dev --ignore-pipfile --deploy
      script:
        - pipenv run pytest --cov-report xml --cov-report term
      after_success:
        - codecov -t $CC_TEST_REPORTER_ID
    - env: ISOLATED=true
      python: '3.6'
      stage: latest-pip
      # get the dependencies
      before_install:
        - pip install pytest codecov
        - pip install "pytest-cov>=2.4.0,<2.6"
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/trusty-media; fi
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg --allow-unauthenticated; fi
      install:
        - pip install -e .
      script:
        - pytest --cov=./moseq2_extract/tests/
    - env: ISOLATED=true
      dist: xenial
      sudo: true
      python: '3.7'
      stage: latest-pip
      # get the dependencies
      before_install:
        - pip install pytest codecov
        - pip install "pytest-cov>=2.4.0,<2.6"
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/xerus-media; fi
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg --allow-unauthenticated; fi
      install:
        - pip install -e .
      script:
        - pytest --cov=./moseq2_extract/tests/