#specs for travis ci
language: python
os:
  - linux
  - osx
python:
  - "3.6"
# get the dependencies
install:
  - pip install .
# install what we need for testing
# ffmpeg from https://gist.github.com/kevinGodell/bd52cd74c8c2d66fb69f108ef223c356
before_install:
  - pip install pytest pytest-cov codecov
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/trusty-media; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install python3; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg; fi
# script for tests... (eventually add coveralls)
script:
  - pytest --cov=./moseq2_extract
after_success:
  - codecov -t 120653e3-fb8e-4928-a751-bd4fdc880ff0
